name: Build App (Xcode 11.5 w/ Swift 5.3)

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build-project:
      runs-on: macos-latest
      steps: 
        - uses: actions/checkout@v2
        - uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: '11.5'
        - uses: YOCKOW/Action-setup-swift@v1
          with:
            swift-version: '5.3'
        - name: Install library npm dependencies
          run: |
            pwd && npm install
        - name: Install pod dependencies
          run: |
            pwd && cd ios && pwd && pod install
        - name: Build app
          run: |       
            pwd && npm run ios
    
